### ISSUE TITLE
library "libbinder.so" not found

### ISSUE THREAD

**Issue by lakersWin** [lcodecorex/KeepAlive#6]
2020-09-19 16:19:50.260 23215-23241/com.boolbird.keepalive E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.boolbird.keepalive:resident, PID: 23215
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libbinder.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.boolbird.keepalive.NativeKeepAlive.<clinit>(NativeKeepAlive.java:7)
        at com.boolbird.keepalive.KeepAliveProcessImpl$1.run(KeepAliveProcessImpl.java:82)

一直是这个错误   ndk版本为16   请问有什么解决的方法吗###

**Comment by a843647878** [comment]
我同样出这个错误    你解决了吗？

**Comment by Zorphling** [comment]
请问你们解决了吗, 是不是需要弄到 jniLibs 里面

**Comment by xiaoyaomeng** [comment]
同样的问题  求解 @lcodecorex
